config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/index'
  get 'pages/about'
  get 'search' => 'posts#search', as: :search

  post '/images/create' => 'images#create'

  root 'pages#index'

  resources :posts do
    resources :comments
  end

  resources :users
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
  belongs_to :user
  validates :body, presence: true,
               length: { minimum: 2}
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
  mount_uploader :file, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :category
  has_many :comments, dependent: :destroy
  validates_presence_of :category
  validates :title, presence: true,
                    length: { minimum: 5 }
  validates :text, presence: true,
                    length: { minimum: 20}

  default_scope -> {order('created_at DESC')}

  def autosave_associated_records_for_category
    if new_category = Category.find_by_topic(category.topic) || Category.create(topic: category.topic)
      self.category = new_category
    else
      self.category_id = self.category.id
    end
    topic = self.category.topic
    topic = "General Stuff" if topic == ""
    self.category.topic = topic.titlecase
    self.category.save!
  end

  def self.calculate_pages
    posts = Post.all.size
    posts_per_page = 10
    pages = posts / posts_per_page
    total_pages = pages if posts % posts_per_page == 0
    total_pages ||= (pages) + 1
  end

  def self.paginate(post_index, page)
    Post.limit(10).offset(post_index * 10)
  end

  def self.search(query)
    query_search = "%#{query.downcase}%"
    results = Post.where('lower(title) LIKE ?', query_search) + Post.where('lower(text) LIKE ?', query_search)
    results.uniq { |post| post.title }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def author?
    role == 'author'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]

	def create
		@post = Post.find(params[:post_id])
		@comment = current_user.comments.build(comment_params.merge(post: @post))
		authorize @comment
		@comment.save!
		redirect_to post_path(@post)
	end

	 def edit
		@post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
		authorize @comment
  end

  def update
		@post = Post.find(params[:post_id])
  	@comment = Comment.find(params[:id])
    authorize @comment
    if @comment.update(comment_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		authorize @comment
		@comment.destroy

		redirect_to post_path(@post)
	end

	private
	def comment_params
		params[:comment].permit(:body)
	end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update]

  def create
    @image = Image.create!(image_params)
    render json: {image:{ url: @image.file.url }}, content_type: "text/html"
  end

  def update
    @image = Image.find(params[:id])
    @image.update!
    render json: { image: { url: @image.file.url } }, content_type: "text/html"
  end

  private
    def image_params
      params.permit(:file)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :update]

  def index
    page = params[:page].try(:to_i) || 1
    @next_page = page + 1
    @post_index = page - 1
    @total_pages = Post.calculate_pages
    @posts = Post.paginate(@post_index, page)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @category = Category.new
    @post = Post.new
    authorize @post
  end

  def create
    @post = current_user.posts.new(post_params)
    authorize @post
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
    @category = Category.find(@post.category.id)
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to posts_path
  end

  def search
    query = params[:query]
    @search_results = Post.search(query)
  end

  private
  def post_params
    params.require(:post).permit(:title, :text, category_attributes: [:id, :topic, :_destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    sanitize Kramdown::Document.new(text).to_html
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<section class="container" style="margin-top: 100px;">
	<% @categories.each do |category| %>
		<% unless category.posts.empty? %>
			<li><%= link_to category.topic, category_path(category.id) %></li>
		<% end %>
	<% end %>
</section>

app/views/categories/show.html.erb
<div class="spacer"></div>
<div class="container">
  <h2><%= @category.topic %> </h2>
  <hr>
  <% @category.posts.each do |p| %>
    <%= link_to post_path(p) do %>
      <p><%= p.title %></p>
    <% end %>
    <hr>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
	<div class="comment-content">
		<p class="comment-name"><strong><%= comment.user.name %></strong></p>
		<p class="comment-body"><%= comment.body %></p>
		<p class="comment-time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>
	
	<div class="comment-controls">
		<% if policy(comment).edit? %>
			<%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %>
			<%= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" } %>
		<% end %>
	</div>
</div>
<hr>

app/views/comments/_form.html.erb
<div class="comment-form">
	<%= form_for [@post, @comment] do |f| %>


		<div class="comment-form-block">
			<%= f.label :body, class: "comment form-body-label" %><br>
			<%= f.text_area :body, rows: '15', class: "comment-form-body" %>
		</div>
			<%= f.submit class: "small-button" %>
	<% end %>
</div>

app/views/comments/edit.html.haml
%header.container
  %h1.page-title Editing comment
%section.container
  = render 'form'
  = link_to 'Back', posts_path

app/views/layouts/_footer.html.erb
		<footer class="footer">
			<p>TribalDev &copy; 2015</p>
		</footer>
	</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Home of TribalDev</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="/assets/tinymce/plugins/uploadimage/plugin.js"></script>
  <meta name=viewport content="width=device-width, initial-scale=1">
</head>
<body>

	<nav class="navbar">
    <span class="mobile-nav">
      &#9776;&nbsp; MENU
    </span>
    <span class="nav-logo">
      TribalDev &nbsp;
    </span>
		<ul class="nav">
			<li class="nav-item">
				<%= link_to root_path do %>
					<span class="icon-home"></span>
				<% end %>
			</li>
			<li class="nav-item">
				<%= link_to "Blog", posts_path %>
			</li>
			<li class="nav-item">
				<%= link_to "About", pages_about_path %>
			</li>
			<% if user_signed_in? %>
				<li class="nav-item"><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
			<% else %>
				<li class="nav-item">
					<%= link_to "Log In", new_user_session_path %>
				</li>
			<% end %>

		</ul>
		<div class="nav-search-bar">
      <form action="/search" method="get">
  			<label for="search"><span class="icon-search" style="margin-right: 5px; font-size: 1.2em;"></span></label>
  			<input type="text" id="search" name="query" class="search text-line">
        <input type="submit" value="Go" class='search-submit'>
      </form>
		</div>
	</nav>

app/views/layouts/application.html.haml
= render 'layouts/header'
= yield
= render 'layouts/footer'

app/views/pages/about.html.erb
<header class="container">
	<h1 class="page-title styled-text" id="about">The Tribe</h1>
</header>

<section class="container">

	<div class="card-holder">
		<div class="card">
			<div class="front">
				<div class="card-front-image">
					<%= image_tag("icons/human-200x200.png") %>
				</div>
				<div class="card-front-text">
					<h2 class="styled-text">Benji</h2>
					<p>Ruby Developer</p>
				</div>
				<p class="card-email">daylightsavings@icloud.com</p>
			</div>
			<div class="back">
				<div class="back-text">
					<h4>Talents</h4>
					<p>HTML5, CSS3, JS, jQuery, Ruby, RoR</p>
				</div>
				<div class="back-bottom">
					<a href="#"><span class="icon-twitter"></span></a>
					<a href="#"><span class="icon-github"></span></a>
					<a href="#"><span class="icon-google"></span></a>
				</div>
			</div>
		</div>

		<div class="card">
			<div class="front">
				<div class="card-front-image">
					<%= image_tag("icons/human-200x200.png") %>
				</div>
				<div class="card-front-text">
					<h2 class="styled-text">Danielle</h2>
					<p>Front-end Web Developer</p>
				</div>
				<p class="card-email">danielle.tinkler@gmail.com</p>
			</div>
			<div class="back">
				<div class="back-text">
					<h4>Talents</h4>
					<p>HTML5, CSS3, JS, jQuery</p>
				</div>
				<div class="back-bottom">
					<a href="https://twitter.com/dashtink"><span class="icon-twitter"></span></a>
					<a href="https://github.com/dashtink"><span class="icon-github"></span></a>
					<a href="https://plus.google.com/u/2/+DanielleTinkler/about"><span class="icon-google"></span></a>
				</div>
			</div>
		</div>

		<div class="card">
			<div class="front">
				<div class="card-front-image">
					<%= image_tag("icons/human-200x200.png") %>
				</div>
				<div class="card-front-text">
					<h2 class="styled-text">Adam</h2>
					<p>Graphics Designer</p>
				</div>
				<p class="card-email">info@adamarvidsson.se</p>
			</div>
			<div class="back">
				<div class="back-text">
					<h4>Talents</h4>
					<p>Graphics Design</p>
				</div>
				<div class="back-bottom">
					<a href="#"><span class="icon-twitter"></span></a>
					<a href="#"><span class="icon-github"></span></a>
					<a href="#"><span class="icon-google"></span></a>
				</div>

			</div>
		</div>

		<div class="card">
			<div class="front">
				<div class="card-front-image">
					<%= image_tag("sam-image.png") %>
				</div>
				<div class="card-front-text">
					<h2 class="styled-text">Sam</h2>
					<p>Ruby Developer</p>
				</div>
				<p class="card-email">510samwebb@gmail.com</p>
			</div>
			<div class="back">
				<div class="back-text">
					<h4>Talents</h4>
					<p>JS, jQuery, Ruby, RoR, Git, Bootstrap</p>
				</div>
				<div class="back-bottom">
					<a href="https://twitter.com/SamTheWebb"><span class="icon-twitter"></span></a>
					<a href="https://github.com/salexzee"><span class="icon-github"></span></a>
					<a href="https://plus.google.com/u/0/105546990448801411596/about"><span class="icon-google"></span></a>
				</div>
			</div>
		</div>

		<div class="card">
			<div class="front">
				<div class="card-front-image">
					<%= image_tag("icons/human-200x200.png") %>
				</div>
				<div class="card-front-text">
					<h2 class="styled-text">Jason</h2>
					<p>Ruby Developer</p>
				</div>
				<p class="card-email">jason.data@roadbytes.me
			</div>
			<div class="back">
				<div class="back-text">
					<h4>Talents</h4>
					<p>HTML5, CSS3, JS, jQuery, Ruby, RoR</p>
				</div>
				<div class="back-bottom">
					<a href="#"><span class="icon-twitter"></span></a>
					<a href="#"><span class="icon-github"></span></a>
					<a href="#"><span class="icon-google"></span></a>
				</div>
			</div>
		</div>

		<div class="card">
			<div class="front">
				<div class="card-front-image">
					<%= image_tag("icons/human-200x200.png") %>
				</div>
				<div class="card-front-text">
					<h2 class="styled-text">Daniel</h2>
					<p>Co-Founder of Karma Bank</p>
				</div>
				<p class="card-email">daniel@tomosovich.com
			</div>
			<div class="back">
				<div class="back-text">
					<h4>Talents</h4>
					<p>RoR, ReactJS, Wordpress</p>
				</div>
				<div class="back-bottom">
					<a href="#"><span class="icon-twitter"></span></a>
					<a href="#"><span class="icon-github"></span></a>
					<a href="#"><span class="icon-google"></span></a>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/pages/index.html.erb
<header class="hero">
	<div id="main-title">
		<h1>TribalDev</h1>
		<h4>reimagine your web-dev experience</h4>
	</div>
</header>

<section class="container">
	<p>Learning Web Development shouldn't be a solitary experience.</p>
	<p>
		 With very little formalized education in this field, community and feedback from your peers is essential. Why go it alone when you can learn with others and accelerate your development experience? Peer-driven education not only makes it easier to learn, but it also makes it much more enjoyable. Come join us at Tribal dev and reimagine your web-dev experience.
	</p>
	<p>
		We're starting out small with a series of blog posts and videos but the more that join in, the more we can accomplish together. That's the idea behind it all. We can accomplish so much more together than we can as individuals. Where we go from here is limited only by what we put into this.
		That's what a tribe's about. We support eachother for the common good.
	</p>
	<p>
		Lets get started! Come join the tribe!
	</p>
	<br>
	<div class="center">
		<a href="/users/sign_up" class='button'>Sign Up</a>
	</div>
	<div class="spacer">
		&nbsp;
	</div>

</section>

app/views/posts/_form.html.erb
<%= tinymce_assets %>

<%= nested_form_for @post do |f| %>
  <div class="form">
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@post.errors.count, "error") %> prohibited
          this post from being saved:
        </h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-block">
      <%= f.label :title, class: 'form-input-label' %><br>
      <%= f.text_field :title, class: 'form-title text-line' %>
    </div>

    <div class="form-block">
      <%= f.text_area :text, :class => "tinymce", :rows => 40, :cols => 120 %>
      <%= tinymce plugins: "uploadimage", uploadimage_form_url: "/images/create" %>
    </div>

    <div class="form-block">
      <label>Category:</label>
      <%= f.fields_for :category, @category do |category_form| %>
        <%= category_form.text_field :topic, class: 'form-title text-line' %>
      <% end %>
    </div>
    <% unless @post.images.blank? %>
      replace, remove or add images:
      <br><br>
    <% end %>
    <p class="kd">This form supports Kramdown syntax. <%= link_to 'Kramdown Quick Reference', 'http://kramdown.gettalong.org/quickref.html', target: "_blank" %></p>

      <%= f.submit class: "button" %>
  </div>

<% end %>

app/views/posts/_paginate.html.erb
<div class="pagination">
  <% unless @post_index == 0 %>
    <%=link_to "prev", posts_path(:page => @post_index), class: "prev-pagination" %>
    &nbsp; &nbsp;
  <% end %>

  <% unless @next_page > @total_pages %>
    <%=link_to "next", posts_path(:page => @next_page), class: "next-pagination" %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <h2>
        <% if post.title.length > 20 %>
          <%= link_to post.title[0..19] + " ...", post%>
        <% else %>
          <%= link_to post.title, post%>
        <% end %>
      </h2>
      <hr>
      <h4><%= post.category.topic %></h4>
      <small>Author: <%= post.user.name %></small>
      <br>
      <small>Created <%= time_ago_in_words(post.created_at) %> ago</small>
      <br><br>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<header class="container">
	<h1 class="page-title">Editing article</h1>
</header>


<section class="container">

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>
</section>

app/views/posts/index.html.erb
<header class="container spacer">
	<h1 class="page-title blog-title styled-text">All Posts</h1>
</header>

<% if policy(Post.new).create? %>
  <%= link_to "New Post", new_post_path, class: 'new-post', data: { no_turbolink: true } %>
<% end %>

<section class="container">
	<%= render partial: "post" %>

	<%= render partial: "paginate" %>

	<br><br><br>
</section>

app/views/posts/index.js.erb
$('#posts').append('<%= escape_javascript render partial: "post" %>');
$('.pagination').replaceWith('<%= escape_javascript render partial: "paginate" %>');
$('.prev-pagination').hide();

app/views/posts/new.html.erb
<header class="container">
	<h1 class="page-title">New Post</h1>
</header>

<section class="container">
  <% if current_user %>
	 <%= render 'form' %>
  <% end %>

	<%= link_to "Back Home", posts_path %>

</section>

app/views/posts/search.html.erb
<section class="container" style="margin-top: 100px;">
  <hr>
  <% if @search_results.blank? %>
    <p class="no-results"><span>?</span>Sorry, no results for that. Search for something else.</p>
    <% else %>
  <% @search_results.each do |post| %>
    <h3><%= link_to post.title, post %></h3>
    <small>
      <%= truncate(post.text, :length => 90, :seperator => ' ...') %>
    </small>
    <hr>
  <% end %>
  <% end %>
</section>

app/views/posts/show.html.erb
<header class="container">
  <h2 class="page-title"><%= @post.title %>
    <% if @post.category %>
      <%= link_to category_path(@post.category) do %>
        <small class='category-sub'>
          #<%= @post.category.topic %>
        </small>
      <% end %>
    <% end %>
  </h2>
</header>


<section class="container post-box">
	<p class="time">Created <%= time_ago_in_words(@post.created_at) %> ago</p>
	<p><%= markdown @post.text %></p>
  <br>
  <% if policy(@post).edit? %>
  	<%= link_to 'Edit', edit_post_path(@post), data: { no_turbolink: true } %>
    <br>
  	<%= link_to "Delete", post_path(@post),
      method: :delete,
      data: { confirm: 'Are you sure you want to delete the post?'}%>
	  <br>
  <% end %>
	<%= link_to "all posts", posts_path %>
</section>
<br>
<br>
<div class="line"></div>

<section class="container comments post-box">

	<h3><%= pluralize(@post.comments.count, 'comment') %></h3>

 	<%= render partial: 'comments/comment', collection: @post.comments %>

  <% if policy(@post.comments).create? %>
  	<h3>Add a comment</h3>
    <% @comment ||= Comment.new %>
  	<%= render partial: 'comments/form' %>
  <% else %>
  <%= link_to 'login to comment', new_user_session_path %>
  <% end %>

</section>

app/views/users/index.html.haml
%br
.container
  %h2
    all users
    %hr
  - @users.each do |user|
    %p
      name:
      = user.name
    %p
      email:
      = user.email
    %p
      Admin:
      = user.role == "author"
    %p
      edit role?:
      %h2
      = form_for @user do |u|
        .field
          = u.label :role
          %br/
          = u.role :role, autofocus: true
        .actions
          = u.submit "Update"